[s]
type = "wave"
form = "square"
bend = 0.3
attack = 0.05

[filter]
type = "filter"
value.index = 1

[bal]
type = "balance"
volume.index = 27
pan.index = 26
pan.bounds = [-1, 1]

[d]
type = "drums"
paths = ["kick.wav", "clap.wav", "hat.wav"]
