[s1]
type = "wave"
form = "saw"
bend = 0.3

[filter1]
type = "filter"
value.controller = "gamepad"
value.index = 13
value.bounds = [0.3, 1]

[bal1]
type = "balance"
volume.index = 28

[s2]
type = "wave"
form = "noise"

[filter2]
type = "filter"
value.controller = "gamepad"
value.index = 12
value.bounds = [0, 0.5]

[bal2]
type = "balance"
volume.index = 28
